# Base image
FROM node:22

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build the application
RUN npm run build

# Expose the port your NestJS app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:prod"]

# # Base image (alpine = much smaller, less memory during build)
# FROM node:22-alpine

# # Create app directory
# WORKDIR /usr/src/app

# # Copy package files
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the application
# COPY . .

# # Expose the port your NestJS app actually runs on (compose maps 6001)
# EXPOSE 6001
